# Generated by Django 3.2.13 on 2022-06-25 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_lock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lock_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 12, 27, 10, 408843)),
        ),
    ]
